// Generated by tools/gen_moduledb.py from data/modules.xml. Do not edit.
// Module descriptions (C) 2006 Christian Schneider / NMedit project, based on Jan Punter's work, GPL.
#include "nmmmoduledb.h"

namespace nmm
{
	namespace
	{
		constexpr ParamDesc g_params_0[] = {{0,0,3,0,2,0}, {1,0,3,0,2,0}, {2,0,3,0,2,0}, {3,0,3,0,2,0}};
		constexpr ParamDesc g_customs_0[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_0[] = {{0,0,0}};
		constexpr ParamDesc g_params_1[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_1[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_1[] = {{0,1,1}, {1,1,2}, {2,1,1}, {3,1,1}};
		constexpr ParamDesc g_params_2[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_2[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_2[] = {{0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_3[] = {{0,0,127,100,7,0}};
		constexpr ParamDesc g_customs_3[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_3[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}};
		constexpr ParamDesc g_params_4[] = {{0,0,127,100,7,0}, {1,0,2,0,2,1}, {2,0,1,0,1,2}};
		constexpr ParamDesc g_customs_4[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_4[] = {{0,0,0}, {1,0,0}};
		constexpr ParamDesc g_params_5[] = {{0,0,127,100,7,0}, {1,0,5,0,3,1}, {2,0,1,0,1,2}};
		constexpr ParamDesc g_customs_5[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_5[] = {{0,0,0}};
		constexpr ParamDesc g_params_7[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,127,64,7,0}, {4,0,3,0,2,4}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,127,0,7,0}, {8,0,127,0,7,0}, {9,0,1,0,1,2}};
		constexpr ParamDesc g_customs_7[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_7[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}, {4,0,0}, {0,1,0}, {1,1,3}};
		constexpr ParamDesc g_params_8[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,3,0,2,4}, {4,0,127,0,7,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,127,0,7,0}, {8,0,1,0,1,2}};
		constexpr ParamDesc g_customs_8[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_8[] = {{0,0,0}, {1,0,1}, {2,0,1}, {3,0,1}, {0,1,0}, {1,1,3}};
		constexpr ParamDesc g_params_9[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,1,1,1,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,1,0,1,2}};
		constexpr ParamDesc g_customs_9[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_9[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}, {1,1,3}};
		constexpr ParamDesc g_params_10[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,127,0,7,0}, {4,0,1,0,1,2}};
		constexpr ParamDesc g_customs_10[] = {{0,0,2,0,8,0}};
		constexpr ConnDesc g_conns_10[] = {{0,0,3}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_11[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,1,0,1,2}};
		constexpr ParamDesc g_customs_11[] = {{0,0,2,0,8,0}};
		constexpr ConnDesc g_conns_11[] = {{0,0,3}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_12[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,1,0,1,2}};
		constexpr ParamDesc g_customs_12[] = {{0,0,2,0,8,0}};
		constexpr ConnDesc g_conns_12[] = {{0,0,3}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_13[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,1,0,1,2}};
		constexpr ParamDesc g_customs_13[] = {{0,0,2,0,8,0}};
		constexpr ConnDesc g_conns_13[] = {{0,0,3}, {1,0,0}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_14[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,3,0,2,4}, {3,0,127,0,7,0}, {4,0,1,0,1,2}};
		constexpr ParamDesc g_customs_14[] = {{0,0,2,0,8,0}};
		constexpr ConnDesc g_conns_14[] = {{0,0,3}, {1,0,0}, {2,0,0}, {3,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_15[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,127,64,7,0}, {4,0,127,64,7,0}, {5,0,127,64,7,0}, {6,0,127,64,7,0}, {7,0,127,64,7,0}, {8,0,127,64,7,0}, {9,0,127,64,7,0}, {10,0,127,64,7,0}, {11,0,127,64,7,0}, {12,0,127,64,7,0}, {13,0,127,64,7,0}, {14,0,127,64,7,0}, {15,0,127,64,7,0}, {16,0,127,15,7,0}, {17,0,16,0,5,0}, {18,0,1,0,1,0}, {19,0,1,0,1,0}, {20,0,1,1,1,0}};
		constexpr ParamDesc g_customs_15[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_15[] = {{0,0,2}, {1,0,2}, {0,1,1}, {1,1,2}, {2,1,2}, {3,1,2}};
		constexpr ParamDesc g_params_16[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_16[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_16[] = {{0,0,1}, {1,0,2}, {0,1,1}};
		constexpr ParamDesc g_params_17[] = {{0,0,127,15,7,0}, {1,0,1,0,1,0}, {2,0,1,0,1,0}, {3,0,1,0,1,0}, {4,0,1,0,1,0}, {5,0,1,0,1,0}, {6,0,1,0,1,0}, {7,0,1,0,1,0}, {8,0,1,0,1,0}, {9,0,1,0,1,0}, {10,0,1,0,1,0}, {11,0,1,0,1,0}, {12,0,1,0,1,0}, {13,0,1,0,1,0}, {14,0,1,0,1,0}, {15,0,1,0,1,0}, {16,0,1,0,1,0}, {17,0,1,0,1,0}, {18,0,1,0,1,0}, {19,0,1,0,1,0}, {20,0,1,0,1,0}, {21,0,1,0,1,0}, {22,0,1,0,1,0}, {23,0,1,0,1,0}, {24,0,1,0,1,0}, {25,0,1,0,1,0}, {26,0,1,0,1,0}, {27,0,1,0,1,0}, {28,0,1,0,1,0}, {29,0,1,0,1,0}, {30,0,1,0,1,0}, {31,0,1,0,1,0}, {32,0,1,0,1,0}, {33,0,1,0,1,0}, {34,0,1,0,1,0}, {35,0,1,0,1,0}};
		constexpr ParamDesc g_customs_17[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_17[] = {{0,0,2}, {1,0,2}, {0,1,2}, {1,1,2}, {2,1,2}, {3,1,2}};
		constexpr ParamDesc g_params_18[] = {{0,0,127,0,7,0}, {1,0,127,64,7,0}};
		constexpr ParamDesc g_customs_18[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_18[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_19[] = {{0,0,127,127,7,0}, {1,0,127,127,7,0}, {2,0,127,127,7,0}};
		constexpr ParamDesc g_customs_19[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_19[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_20[] = {{0,0,2,0,2,0}, {1,0,127,0,7,0}, {2,0,127,0,7,0}, {3,0,127,64,7,0}, {4,0,127,0,7,0}, {5,0,1,0,1,0}};
		constexpr ParamDesc g_customs_20[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_20[] = {{0,0,0}, {1,0,2}, {2,0,2}, {3,0,1}, {0,1,1}, {1,1,0}};
		constexpr ParamDesc g_params_21[] = {{0,0,127,0,7,0}, {1,0,127,20,7,0}, {2,0,42,20,6,0}, {3,0,66,20,7,0}, {4,0,42,30,6,0}, {5,0,24,12,5,0}, {6,0,1,0,1,0}, {7,0,1,0,1,0}, {8,0,1,0,1,0}};
		constexpr ParamDesc g_customs_21[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_21[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_22[] = {{0,0,127,0,7,4}};
		constexpr ParamDesc g_customs_22[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_22[] = {{0,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_23[] = {{0,0,127,0,7,0}, {1,0,127,77,7,0}, {2,0,127,0,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,127,0,7,0}, {8,0,1,0,1,0}};
		constexpr ParamDesc g_customs_23[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_23[] = {{0,0,2}, {1,0,2}, {2,0,1}, {3,0,1}, {4,0,1}, {5,0,1}, {6,0,0}, {7,0,1}, {0,1,1}, {1,1,0}};
		constexpr ParamDesc g_params_24[] = {{0,0,127,64,7,0}, {1,0,2,0,2,0}, {2,0,4,0,3,4}, {3,0,127,0,7,0}, {4,0,1,0,1,0}, {5,0,127,0,7,0}, {6,0,127,64,7,0}, {7,0,1,0,1,2}};
		constexpr ParamDesc g_customs_24[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_24[] = {{0,0,1}, {1,0,2}, {0,1,3}, {1,1,1}};
		constexpr ParamDesc g_params_25[] = {{0,0,127,64,7,0}, {1,0,2,0,2,0}, {2,0,127,64,7,0}, {3,0,127,0,7,0}, {4,0,1,0,1,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,127,64,7,0}};
		constexpr ParamDesc g_customs_25[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_25[] = {{0,0,1}, {1,0,2}, {2,0,1}, {0,1,1}, {1,1,3}};
		constexpr ParamDesc g_params_26[] = {{0,0,127,64,7,0}, {1,0,2,0,2,0}, {2,0,4,0,3,4}, {3,0,127,0,7,0}, {4,0,1,0,1,0}, {5,0,1,0,1,2}};
		constexpr ParamDesc g_customs_26[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_26[] = {{0,0,1}, {0,1,1}, {1,1,3}};
		constexpr ParamDesc g_params_27[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_27[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_27[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_28[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_28[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_28[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_29[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_29[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_29[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_30[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_30[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_30[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_31[] = {{0,0,127,0,7,0}};
		constexpr ParamDesc g_customs_31[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_31[] = {{0,1,0}};
		constexpr ParamDesc g_params_32[] = {{0,0,127,127,7,0}, {1,0,127,127,7,0}, {2,0,127,127,7,0}, {3,0,127,127,7,0}, {4,0,127,127,7,0}, {5,0,127,127,7,0}, {6,0,127,127,7,0}, {7,0,127,127,7,0}, {8,0,127,127,7,0}, {9,0,127,127,7,0}, {10,0,127,127,7,0}, {11,0,127,127,7,0}, {12,0,127,127,7,0}, {13,0,127,127,7,0}, {14,0,1,0,1,0}};
		constexpr ParamDesc g_customs_32[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_32[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_33[] = {{0,0,1,0,1,0}, {1,0,1,0,1,0}};
		constexpr ParamDesc g_customs_33[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_33[] = {{0,0,2}, {0,1,1}};
		constexpr ParamDesc g_params_34[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_34[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_34[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_35[] = {{0,0,127,0,7,0}};
		constexpr ParamDesc g_customs_35[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_35[] = {{0,1,2}};
		constexpr ParamDesc g_params_36[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_36[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_36[] = {{0,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_37[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_37[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_37[] = {{0,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_38[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_38[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_38[] = {{0,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_39[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_39[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_39[] = {{0,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_40[] = {{0,0,127,100,7,0}, {1,0,127,100,7,0}, {2,0,127,100,7,0}, {3,0,127,100,7,0}, {4,0,127,100,7,0}, {5,0,127,100,7,0}, {6,0,127,100,7,0}, {7,0,127,100,7,0}, {8,0,1,0,1,0}};
		constexpr ParamDesc g_customs_40[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_40[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}, {4,0,0}, {5,0,0}, {6,0,0}, {7,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_43[] = {{0,0,127,64,7,0}, {1,0,1,0,1,0}};
		constexpr ParamDesc g_customs_43[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_43[] = {{0,1,1}};
		constexpr ParamDesc g_params_44[] = {{0,0,1,0,1,0}};
		constexpr ParamDesc g_customs_44[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_44[] = {{0,0,0}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_45[] = {{0,0,8,0,4,0}, {1,0,8,1,4,0}, {2,0,8,2,4,0}, {3,0,127,100,7,0}, {4,0,127,64,7,0}, {5,0,127,0,7,0}, {6,0,127,64,7,0}, {7,0,127,0,7,0}, {8,0,127,64,7,0}};
		constexpr ParamDesc g_customs_45[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_45[] = {{0,0,0}, {1,0,1}, {2,0,1}, {0,1,0}};
		constexpr ParamDesc g_params_46[] = {{0,0,127,0,7,0}, {1,0,127,32,7,0}, {2,0,127,77,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,127,0,7,0}};
		constexpr ParamDesc g_customs_46[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_46[] = {{0,0,2}, {1,0,1}, {2,0,1}, {3,0,1}, {4,0,0}, {5,0,1}, {0,1,1}, {1,1,0}};
		constexpr ParamDesc g_params_47[] = {{0,0,127,0,7,0}, {1,0,127,64,7,0}};
		constexpr ParamDesc g_customs_47[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_47[] = {{0,0,0}, {1,0,0}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_48[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_48[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_48[] = {{0,0,1}, {1,0,2}, {0,1,1}};
		constexpr ParamDesc g_params_50[] = {{0,0,127,60,7,0}, {1,0,127,0,7,0}, {2,0,1,1,1,0}};
		constexpr ParamDesc g_customs_50[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_50[] = {{0,0,0}, {0,1,0}, {1,1,0}, {2,1,0}};
		constexpr ParamDesc g_params_49[] = {{0,0,127,60,7,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,127,0,7,0}};
		constexpr ParamDesc g_customs_49[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_49[] = {{0,0,1}, {1,0,0}, {0,1,0}, {1,1,0}, {2,1,0}};
		constexpr ParamDesc g_params_51[] = {{0,0,3,0,2,4}, {1,0,1,1,1,0}, {2,0,127,0,7,0}, {3,0,127,60,7,0}, {4,0,127,64,7,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,1,1,1,4}, {8,0,127,0,7,0}, {9,0,1,0,1,0}};
		constexpr ParamDesc g_customs_51[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_51[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_52[] = {{0,0,127,127,7,0}, {1,0,127,45,7,0}, {2,0,127,64,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,127,30,7,0}, {6,0,127,30,7,0}, {7,0,127,30,7,0}, {8,0,127,0,7,0}, {9,0,4,0,3,0}, {10,0,2,0,2,0}};
		constexpr ParamDesc g_customs_52[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_52[] = {{0,0,2}, {1,0,0}, {2,0,1}, {0,1,1}, {1,1,0}};
		constexpr ParamDesc g_params_53[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_53[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_53[] = {{0,0,2}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_54[] = {{0,0,12,0,4,0}};
		constexpr ParamDesc g_customs_54[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_54[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_57[] = {{0,0,2,0,2,0}, {1,0,1,0,1,0}};
		constexpr ParamDesc g_customs_57[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_57[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_58[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}, {2,0,127,25,7,0}, {3,0,127,25,7,0}, {4,0,127,25,7,0}, {5,0,127,25,7,0}, {6,0,127,25,7,0}, {7,0,127,25,7,0}, {8,0,127,25,7,0}, {9,0,127,25,7,0}, {10,0,2,0,2,0}, {11,0,127,25,7,0}, {12,0,127,25,7,0}, {13,0,127,25,7,0}, {14,0,127,25,7,0}, {15,0,1,0,1,2}};
		constexpr ParamDesc g_customs_58[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_58[] = {{0,0,2}, {1,0,1}, {2,0,1}, {0,1,0}};
		constexpr ParamDesc g_params_59[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_59[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_59[] = {{0,0,1}, {0,1,2}};
		constexpr ParamDesc g_params_61[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}, {2,0,1,0,1,0}};
		constexpr ParamDesc g_customs_61[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_61[] = {{0,0,0}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_62[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}};
		constexpr ParamDesc g_customs_62[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_62[] = {{1,0,1}, {0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_63[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_63[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_63[] = {{0,1,1}, {1,1,2}, {2,1,1}, {3,1,1}};
		constexpr ParamDesc g_params_64[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_64[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_64[] = {{0,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_65[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_65[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_65[] = {{0,1,2}, {1,1,2}, {2,1,2}};
		constexpr ParamDesc g_params_66[] = {{0,0,1,0,1,0}, {1,0,127,127,7,0}, {2,0,1,0,1,0}, {3,0,127,127,7,0}, {4,0,1,0,1,0}};
		constexpr ParamDesc g_customs_66[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_66[] = {{0,0,1}, {1,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_67[] = {{0,0,127,60,7,0}};
		constexpr ParamDesc g_customs_67[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_67[] = {{0,1,2}, {1,1,1}, {2,1,1}};
		constexpr ParamDesc g_params_68[] = {{0,0,127,64,7,0}, {1,0,1,1,1,0}};
		constexpr ParamDesc g_customs_68[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_68[] = {{0,0,2}, {0,1,2}, {1,1,2}, {2,1,3}, {3,1,2}};
		constexpr ParamDesc g_params_69[] = {{0,0,127,0,7,0}};
		constexpr ParamDesc g_customs_69[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_69[] = {{0,0,2}, {1,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_70[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_70[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_70[] = {{0,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_71[] = {{0,0,127,0,7,0}, {1,0,127,20,7,0}};
		constexpr ParamDesc g_customs_71[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_71[] = {{0,0,0}, {0,1,1}};
		constexpr ParamDesc g_params_72[] = {{0,0,127,0,7,0}};
		constexpr ParamDesc g_customs_72[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_72[] = {{0,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_73[] = {{0,0,2,0,2,0}};
		constexpr ParamDesc g_customs_73[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_73[] = {{0,0,2}, {1,0,2}, {0,1,2}};
		constexpr ParamDesc g_params_74[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}};
		constexpr ParamDesc g_customs_74[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_74[] = {{0,0,0}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_75[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}};
		constexpr ParamDesc g_customs_75[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_75[] = {{0,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_76[] = {{0,0,1,1,1,0}};
		constexpr ParamDesc g_customs_76[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_76[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_77[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_77[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_77[] = {{1,0,2}, {0,0,2}, {0,1,2}, {1,1,2}, {2,1,2}};
		constexpr ParamDesc g_params_78[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}};
		constexpr ParamDesc g_customs_78[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_78[] = {{0,0,0}, {1,0,1}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_79[] = {{0,0,3,0,2,0}, {1,0,127,0,7,0}, {2,0,127,0,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,1,0,1,2}};
		constexpr ParamDesc g_customs_79[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_79[] = {{0,0,0}, {1,0,0}, {2,0,0}, {3,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_80[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,4,0,3,4}, {3,0,1,0,1,0}, {4,0,1,0,1,2}};
		constexpr ParamDesc g_customs_80[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_80[] = {{0,0,3}, {1,0,2}, {0,1,1}};
		constexpr ParamDesc g_params_81[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_81[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_81[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_82[] = {{0,0,2,0,2,0}};
		constexpr ParamDesc g_customs_82[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_82[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_83[] = {{0,0,4,2,3,0}};
		constexpr ParamDesc g_customs_83[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_83[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_84[] = {{0,0,127,0,7,0}, {1,0,127,77,7,0}, {2,0,1,0,1,0}};
		constexpr ParamDesc g_customs_84[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_84[] = {{0,0,2}, {1,0,0}, {2,0,1}, {0,1,1}, {1,1,0}};
		constexpr ParamDesc g_params_85[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,1,0,1,0}, {3,0,127,0,7,0}, {4,0,1,0,1,2}};
		constexpr ParamDesc g_customs_85[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_85[] = {{0,0,3}, {1,0,0}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_86[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_86[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_86[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_87[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_87[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_87[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_88[] = {{0,0,3,0,2,1}, {1,0,127,0,7,0}, {2,0,1,0,1,2}};
		constexpr ParamDesc g_customs_88[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_88[] = {{0,0,0}, {0,1,0}, {1,1,0}, {2,1,0}, {3,1,0}};
		constexpr ParamDesc g_params_89[] = {{0,0,0,0,0,0}};
		constexpr ParamDesc g_customs_89[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_89[] = {{0,0,1}, {1,0,1}, {0,1,2}};
		constexpr ParamDesc g_params_90[] = {{0,0,127,60,7,0}, {1,0,127,60,7,0}, {2,0,127,60,7,0}, {3,0,127,60,7,0}, {4,0,127,60,7,0}, {5,0,127,60,7,0}, {6,0,127,60,7,0}, {7,0,127,60,7,0}, {8,0,127,60,7,0}, {9,0,127,60,7,0}, {10,0,127,60,7,0}, {11,0,127,60,7,0}, {12,0,127,60,7,0}, {13,0,127,60,7,0}, {14,0,127,60,7,0}, {15,0,127,60,7,0}, {16,0,127,15,7,0}, {17,0,16,0,5,0}, {18,0,1,0,1,0}, {19,0,1,0,1,0}, {20,0,1,1,1,0}};
		constexpr ParamDesc g_customs_90[] = {{0,1,6,0,8,0}, {1,6,117,0,8,0}};
		constexpr ConnDesc g_conns_90[] = {{0,0,2}, {1,0,2}, {0,1,1}, {1,1,2}, {2,1,2}, {3,1,2}};
		constexpr ParamDesc g_params_91[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,127,64,7,0}, {4,0,127,64,7,0}, {5,0,127,64,7,0}, {6,0,127,64,7,0}, {7,0,127,64,7,0}, {8,0,127,64,7,0}, {9,0,127,64,7,0}, {10,0,127,64,7,0}, {11,0,127,64,7,0}, {12,0,127,64,7,0}, {13,0,127,64,7,0}, {14,0,127,64,7,0}, {15,0,127,64,7,0}, {16,0,127,15,7,0}, {17,0,1,0,1,0}, {18,0,1,0,1,0}};
		constexpr ParamDesc g_customs_91[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_91[] = {{0,0,2}, {1,0,2}, {0,1,1}, {1,1,2}, {2,1,2}};
		constexpr ParamDesc g_params_92[] = {{0,0,127,60,7,0}, {1,0,127,0,7,0}, {2,0,127,0,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}, {5,0,2,0,2,4}, {6,0,1,0,1,0}};
		constexpr ParamDesc g_customs_92[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_92[] = {{0,0,1}, {1,0,1}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_94[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,1,0,1,0}};
		constexpr ParamDesc g_customs_94[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_94[] = {{0,0,0}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_95[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,1,0,1,0}, {4,0,127,0,7,0}, {5,0,127,64,7,0}, {6,0,1,0,1,2}};
		constexpr ParamDesc g_customs_95[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_95[] = {{0,0,0}, {1,0,0}, {2,0,1}, {0,1,0}};
		constexpr ParamDesc g_params_96[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,1,1,1,0}, {3,0,1,0,1,2}, {4,0,127,0,7,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}};
		constexpr ParamDesc g_customs_96[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_96[] = {{0,0,1}, {1,0,1}, {2,0,1}, {0,1,0}, {1,1,3}};
		constexpr ParamDesc g_params_97[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,1,0,7,0}, {3,0,127,0,7,0}, {4,0,127,0,7,0}};
		constexpr ParamDesc g_customs_97[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_97[] = {{0,0,1}, {1,0,1}, {0,1,3}};
		constexpr ParamDesc g_params_98[] = {{0,0,127,0,7,0}, {1,0,1,0,1,0}, {2,0,1,0,1,0}, {3,0,1,0,1,0}, {4,0,1,0,1,0}, {5,0,1,0,1,0}, {6,0,1,0,1,0}, {7,0,1,0,1,0}, {8,0,1,0,1,0}, {9,0,1,0,1,0}, {10,0,1,0,1,0}, {11,0,1,0,1,0}, {12,0,1,0,1,0}, {13,0,1,0,1,0}};
		constexpr ParamDesc g_customs_98[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_98[] = {{0,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_99[] = {{0,0,127,0,7,0}, {1,0,127,0,7,0}, {2,0,1,0,1,0}, {3,0,127,16,7,0}, {4,0,1,0,1,0}};
		constexpr ParamDesc g_customs_99[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_99[] = {{0,0,2}, {1,0,2}, {2,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_100[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}};
		constexpr ParamDesc g_customs_100[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_100[] = {{0,0,1}, {1,0,2}, {2,0,1}, {0,1,1}, {1,1,2}, {2,1,1}};
		constexpr ParamDesc g_params_102[] = {{0,0,127,60,7,0}, {1,0,1,0,1,0}, {2,0,127,0,7,0}, {3,0,127,64,7,0}, {4,0,127,0,7,0}, {5,0,127,64,7,0}, {6,0,5,0,3,0}, {7,0,127,64,7,0}, {8,0,1,0,1,0}, {9,0,127,64,7,0}, {10,0,127,127,7,0}};
		constexpr ParamDesc g_customs_102[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_102[] = {{0,0,0}, {1,0,1}, {2,0,1}, {0,1,0}};
		constexpr ParamDesc g_params_103[] = {{0,0,127,60,7,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,1,0,1,0}, {4,0,127,127,7,0}};
		constexpr ParamDesc g_customs_103[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_103[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_104[] = {{0,0,127,60,7,0}, {1,0,127,0,7,0}, {2,0,1,0,1,0}, {3,0,1,0,1,0}, {4,0,127,127,7,0}};
		constexpr ParamDesc g_customs_104[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_104[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_105[] = {{0,0,127,0,7,0}, {1,0,127,20,7,0}, {2,0,84,24,7,0}, {3,0,66,20,7,0}, {4,0,72,0,7,0}, {5,0,127,0,7,0}, {6,0,1,0,1,0}, {7,0,1,0,1,0}, {8,0,1,0,1,0}};
		constexpr ParamDesc g_customs_105[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_105[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_106[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,100,7,0}, {3,0,127,64,7,0}, {4,0,127,64,7,0}, {5,0,127,100,7,0}, {6,0,127,64,7,0}, {7,0,127,64,7,0}, {8,0,127,100,7,0}, {9,0,127,64,7,0}, {10,0,127,64,7,0}, {11,0,127,100,7,0}, {12,0,127,64,7,0}, {13,0,127,64,7,0}, {14,0,127,100,7,0}, {15,0,127,64,7,0}, {16,0,127,64,7,0}, {17,0,127,100,7,0}, {18,0,1,0,1,2}, {19,0,1,0,1,2}, {20,0,1,0,1,2}, {21,0,1,0,1,2}, {22,0,1,0,1,2}, {23,0,1,0,1,2}};
		constexpr ParamDesc g_customs_106[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_106[] = {{0,0,3}, {1,0,0}, {2,0,0}, {3,0,0}, {4,0,0}, {5,0,0}, {6,0,0}, {7,0,0}, {8,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_107[] = {{0,0,127,64,7,0}, {1,0,127,64,7,0}, {2,0,127,64,7,0}, {3,0,1,1,1,4}, {4,0,127,0,7,0}, {5,0,127,0,7,0}, {6,0,127,0,7,0}, {7,0,127,0,7,0}, {8,0,1,0,1,0}, {9,0,1,0,1,2}};
		constexpr ParamDesc g_customs_107[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_107[] = {{0,0,0}, {1,0,1}, {2,0,1}, {3,0,1}, {0,1,0}, {1,1,3}};
		constexpr ParamDesc g_params_108[] = {{0,0,16,1,5,0}, {1,0,16,2,5,0}, {2,0,16,3,5,0}, {3,0,16,4,5,0}, {4,0,16,5,5,0}, {5,0,16,6,5,0}, {6,0,16,7,5,0}, {7,0,16,8,5,0}, {8,0,16,9,5,0}, {9,0,16,10,5,0}, {10,0,16,11,5,0}, {11,0,16,12,5,0}, {12,0,16,13,5,0}, {13,0,16,14,5,0}, {14,0,16,15,5,0}, {15,0,16,16,5,0}, {16,0,127,64,7,0}, {17,0,1,0,1,0}, {18,0,1,0,1,0}};
		constexpr ParamDesc g_customs_108[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_108[] = {{0,0,0}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_110[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_110[] = {{0,0,1,0,8,0}};
		constexpr ConnDesc g_conns_110[] = {{0,0,3}, {0,1,1}};
		constexpr ParamDesc g_params_111[] = {{0,0,127,64,7,0}, {1,0,1,0,1,0}};
		constexpr ParamDesc g_customs_111[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_111[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_112[] = {{0,0,127,64,7,0}, {1,0,1,0,1,0}};
		constexpr ParamDesc g_customs_112[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_112[] = {{0,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_113[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_113[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_113[] = {{0,0,0}, {0,1,0}, {1,1,0}};
		constexpr ParamDesc g_params_114[] = {{0,0,127,64,7,0}};
		constexpr ParamDesc g_customs_114[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_114[] = {{0,0,0}, {1,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_115[] = {{0,0,127,0,7,0}, {1,0,48,24,6,0}, {2,0,127,64,7,0}, {3,0,48,24,6,0}};
		constexpr ParamDesc g_customs_115[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_115[] = {{0,0,1}, {1,0,1}, {0,1,1}};
		constexpr ParamDesc g_params_117[] = {{0,0,127,0,7,0}, {1,0,127,64,7,0}};
		constexpr ParamDesc g_customs_117[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_117[] = {{0,0,0}, {1,0,0}, {2,0,0}, {0,1,0}};
		constexpr ParamDesc g_params_118[] = {{0,0,11,0,4,0}, {1,0,127,64,7,0}, {2,0,127,0,7,0}, {3,0,1,0,1,0}, {4,0,1,0,1,0}};
		constexpr ParamDesc g_customs_118[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_118[] = {{0,0,0}, {1,0,1}, {0,1,0}};
		constexpr ParamDesc g_params_127[] = {{0,0,1,0,1,0}};
		constexpr ParamDesc g_customs_127[] = {{0,0,0,0,0,0}};
		constexpr ConnDesc g_conns_127[] = {{0,1,0}, {1,1,0}};

		constexpr ModuleDesc g_modules[] = {
			{0, "Morph", g_params_0, 4, g_customs_0, 0, g_conns_0, 0},
			{1, "Keyboard", g_params_1, 0, g_customs_1, 0, g_conns_1, 4},
			{2, "AudioIn", g_params_2, 0, g_customs_2, 0, g_conns_2, 2},
			{3, "4Output", g_params_3, 1, g_customs_3, 0, g_conns_3, 4},
			{4, "2Output", g_params_4, 3, g_customs_4, 0, g_conns_4, 2},
			{5, "1Output", g_params_5, 3, g_customs_5, 0, g_conns_5, 1},
			{7, "OscA", g_params_7, 10, g_customs_7, 1, g_conns_7, 7},
			{8, "OscB", g_params_8, 9, g_customs_8, 1, g_conns_8, 6},
			{9, "OscC", g_params_9, 6, g_customs_9, 1, g_conns_9, 5},
			{10, "OscSlvB", g_params_10, 5, g_customs_10, 1, g_conns_10, 3},
			{11, "OscSlvC", g_params_11, 4, g_customs_11, 1, g_conns_11, 3},
			{12, "OscSlvD", g_params_12, 4, g_customs_12, 1, g_conns_12, 3},
			{13, "OscSlvE", g_params_13, 4, g_customs_13, 1, g_conns_13, 4},
			{14, "OscSlvA", g_params_14, 5, g_customs_14, 1, g_conns_14, 5},
			{15, "NoteSeqA", g_params_15, 21, g_customs_15, 0, g_conns_15, 6},
			{16, "PortamentoB", g_params_16, 1, g_customs_16, 0, g_conns_16, 3},
			{17, "EventSeq", g_params_17, 36, g_customs_17, 0, g_conns_17, 6},
			{18, "X-Fade", g_params_18, 2, g_customs_18, 0, g_conns_18, 4},
			{19, "Mixer (3)", g_params_19, 3, g_customs_19, 0, g_conns_19, 4},
			{20, "ADSR", g_params_20, 6, g_customs_20, 0, g_conns_20, 6},
			{21, "Compressor", g_params_21, 9, g_customs_21, 0, g_conns_21, 5},
			{22, "PartialGen", g_params_22, 1, g_customs_22, 0, g_conns_22, 2},
			{23, "Mod-Env", g_params_23, 9, g_customs_23, 0, g_conns_23, 10},
			{24, "LFOA", g_params_24, 8, g_customs_24, 0, g_conns_24, 4},
			{25, "LFOB", g_params_25, 8, g_customs_25, 0, g_conns_25, 5},
			{26, "LFOC", g_params_26, 6, g_customs_26, 0, g_conns_26, 3},
			{27, "LFOSlvB", g_params_27, 1, g_customs_27, 1, g_conns_27, 2},
			{28, "LFOSlvC", g_params_28, 1, g_customs_28, 1, g_conns_28, 2},
			{29, "LFOSlvD", g_params_29, 1, g_customs_29, 1, g_conns_29, 2},
			{30, "LFOSlvE", g_params_30, 1, g_customs_30, 1, g_conns_30, 2},
			{31, "Noise", g_params_31, 1, g_customs_31, 0, g_conns_31, 1},
			{32, "FilterBank", g_params_32, 15, g_customs_32, 0, g_conns_32, 2},
			{33, "ClkRndGen", g_params_33, 2, g_customs_33, 0, g_conns_33, 2},
			{34, "RndStepGen", g_params_34, 1, g_customs_34, 1, g_conns_34, 2},
			{35, "RndPulsGen", g_params_35, 1, g_customs_35, 0, g_conns_35, 1},
			{36, "PosEdgeDelay", g_params_36, 1, g_customs_36, 0, g_conns_36, 2},
			{37, "LogicDelay", g_params_37, 1, g_customs_37, 0, g_conns_37, 2},
			{38, "Pulse", g_params_38, 1, g_customs_38, 0, g_conns_38, 2},
			{39, "Smooth", g_params_39, 1, g_customs_39, 0, g_conns_39, 2},
			{40, "Mixer (8)", g_params_40, 9, g_customs_40, 0, g_conns_40, 9},
			{43, "Constant", g_params_43, 2, g_customs_43, 0, g_conns_43, 1},
			{44, "GainControl", g_params_44, 1, g_customs_44, 0, g_conns_44, 3},
			{45, "VocalFilter", g_params_45, 9, g_customs_45, 0, g_conns_45, 4},
			{46, "AHD", g_params_46, 6, g_customs_46, 0, g_conns_46, 8},
			{47, "Pan", g_params_47, 2, g_customs_47, 0, g_conns_47, 4},
			{48, "PortamentoA", g_params_48, 1, g_customs_48, 0, g_conns_48, 3},
			{49, "FilterD", g_params_49, 4, g_customs_49, 1, g_conns_49, 5},
			{50, "FilterC", g_params_50, 3, g_customs_50, 1, g_conns_50, 4},
			{51, "FilterE", g_params_51, 10, g_customs_51, 1, g_conns_51, 5},
			{52, "Multi-Env", g_params_52, 11, g_customs_52, 0, g_conns_52, 5},
			{53, "Sample&Hold", g_params_53, 0, g_customs_53, 0, g_conns_53, 3},
			{54, "Quantizer", g_params_54, 1, g_customs_54, 0, g_conns_54, 2},
			{57, "InvLevShift", g_params_57, 2, g_customs_57, 0, g_conns_57, 2},
			{58, "DrumSynth", g_params_58, 16, g_customs_58, 0, g_conns_58, 4},
			{59, "CompareLev", g_params_59, 1, g_customs_59, 0, g_conns_59, 2},
			{61, "Clip", g_params_61, 3, g_customs_61, 0, g_conns_61, 3},
			{62, "Overdrive", g_params_62, 2, g_customs_62, 0, g_conns_62, 3},
			{63, "KeyboardPatch", g_params_63, 0, g_customs_63, 0, g_conns_63, 4},
			{64, "NegEdgeDelay", g_params_64, 1, g_customs_64, 0, g_conns_64, 2},
			{65, "MIDIGlobal", g_params_65, 0, g_customs_65, 0, g_conns_65, 3},
			{66, "ControlMixer", g_params_66, 5, g_customs_66, 0, g_conns_66, 3},
			{67, "NoteDetect", g_params_67, 1, g_customs_67, 0, g_conns_67, 3},
			{68, "ClkGen", g_params_68, 2, g_customs_68, 0, g_conns_68, 5},
			{69, "ClkDiv", g_params_69, 1, g_customs_69, 0, g_conns_69, 3},
			{70, "LogicInv", g_params_70, 0, g_customs_70, 0, g_conns_70, 2},
			{71, "EnvFollower", g_params_71, 2, g_customs_71, 0, g_conns_71, 2},
			{72, "NoteScaler", g_params_72, 1, g_customs_72, 0, g_conns_72, 2},
			{73, "LogicProc", g_params_73, 1, g_customs_73, 0, g_conns_73, 3},
			{74, "WaveWrap", g_params_74, 2, g_customs_74, 0, g_conns_74, 3},
			{75, "NoteQuant", g_params_75, 2, g_customs_75, 0, g_conns_75, 2},
			{76, "OnOff", g_params_76, 1, g_customs_76, 0, g_conns_76, 2},
			{77, "ClkDivFix", g_params_77, 0, g_customs_77, 0, g_conns_77, 5},
			{78, "Delay", g_params_78, 2, g_customs_78, 0, g_conns_78, 4},
			{79, "4-1Switch", g_params_79, 6, g_customs_79, 0, g_conns_79, 5},
			{80, "LFOSlvA", g_params_80, 5, g_customs_80, 1, g_conns_80, 3},
			{81, "Amplifier", g_params_81, 1, g_customs_81, 0, g_conns_81, 2},
			{82, "Diode", g_params_82, 1, g_customs_82, 0, g_conns_82, 2},
			{83, "Shaper", g_params_83, 1, g_customs_83, 0, g_conns_83, 2},
			{84, "AD-Env", g_params_84, 3, g_customs_84, 0, g_conns_84, 5},
			{85, "OscSlvFM", g_params_85, 5, g_customs_85, 1, g_conns_85, 4},
			{86, "FilterA", g_params_86, 1, g_customs_86, 0, g_conns_86, 2},
			{87, "FilterB", g_params_87, 1, g_customs_87, 0, g_conns_87, 2},
			{88, "1-4Switch", g_params_88, 3, g_customs_88, 0, g_conns_88, 5},
			{89, "CompareAB", g_params_89, 0, g_customs_89, 0, g_conns_89, 3},
			{90, "NoteSeqB", g_params_90, 21, g_customs_90, 2, g_conns_90, 6},
			{91, "CtrlSeq", g_params_91, 19, g_customs_91, 0, g_conns_91, 5},
			{92, "FilterF", g_params_92, 7, g_customs_92, 1, g_conns_92, 4},
			{94, "StereoChorus", g_params_94, 3, g_customs_94, 0, g_conns_94, 3},
			{95, "PercOsc", g_params_95, 7, g_customs_95, 1, g_conns_95, 4},
			{96, "FormantOsc", g_params_96, 7, g_customs_96, 1, g_conns_96, 5},
			{97, "MasterOsc", g_params_97, 5, g_customs_97, 1, g_conns_97, 3},
			{98, "KeyQuant", g_params_98, 14, g_customs_98, 0, g_conns_98, 2},
			{99, "PatternGen", g_params_99, 5, g_customs_99, 0, g_conns_99, 4},
			{100, "KeybSplit", g_params_100, 2, g_customs_100, 0, g_conns_100, 6},
			{102, "Phaser", g_params_102, 11, g_customs_102, 0, g_conns_102, 4},
			{103, "EqMid", g_params_103, 5, g_customs_103, 0, g_conns_103, 2},
			{104, "EqShelving", g_params_104, 5, g_customs_104, 0, g_conns_104, 2},
			{105, "Expander", g_params_105, 9, g_customs_105, 0, g_conns_105, 5},
			{106, "OscSineBank", g_params_106, 24, g_customs_106, 0, g_conns_106, 10},
			{107, "SpectralOsc", g_params_107, 10, g_customs_107, 1, g_conns_107, 6},
			{108, "Vocoder", g_params_108, 19, g_customs_108, 0, g_conns_108, 3},
			{110, "RandomGen", g_params_110, 1, g_customs_110, 1, g_conns_110, 2},
			{111, "LevMult", g_params_111, 2, g_customs_111, 0, g_conns_111, 2},
			{112, "LevAdd", g_params_112, 2, g_customs_112, 0, g_conns_112, 2},
			{113, "1to2Fade", g_params_113, 1, g_customs_113, 0, g_conns_113, 3},
			{114, "2to1Fade", g_params_114, 1, g_customs_114, 0, g_conns_114, 3},
			{115, "NoteVelScal", g_params_115, 4, g_customs_115, 0, g_conns_115, 3},
			{117, "RingMod", g_params_117, 2, g_customs_117, 0, g_conns_117, 4},
			{118, "Digitizer", g_params_118, 5, g_customs_118, 0, g_conns_118, 3},
			{127, "PolyAreaIn", g_params_127, 1, g_customs_127, 0, g_conns_127, 2},
		};
	}

	const ModuleDesc* ModuleDb::find(const int _index)
	{
		for (const auto& m : g_modules)
			if(m.index == _index) return &m;
		return nullptr;
	}

	size_t ModuleDb::count() { return sizeof(g_modules) / sizeof(g_modules[0]); }
	const ModuleDesc* ModuleDb::at(const size_t _i) { return &g_modules[_i]; }
}
