#!/usr/bin/env python3
"""Generate nmmLib/nmmmoduledb.cpp from data/modules.xml (nmedit/Nomad module descriptions, GPL).

Only what the patch loader needs is kept: module index and name, the "parameter" class
parameters in dump order (max value decides the bit width in the parameter dump), the
number of "custom" class parameters and their defaults, and the connectors (index, direction,
signal type = cable colour).
"""
import sys, os
import xml.etree.ElementTree as ET

NS = {'m': 'http://nmedit.sf.net/ns/ModuleDescriptions'}
SIGNALS = {'audio': 0, 'control': 1, 'logic': 2, 'master-slave': 3, 'user1': 4, 'user2': 5, 'none': 6}

def esc(s):
    return s.replace('\\', '\\\\').replace('"', '\\"')

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'data/modules.xml'
    dst = sys.argv[2] if len(sys.argv) > 2 else 'nmmLib/nmmmoduledb.cpp'
    root = ET.parse(src).getroot()
    body = root.find('m:body', NS)
    out = []
    out.append('// Generated by tools/gen_moduledb.py from data/modules.xml. Do not edit.')
    out.append('// Module descriptions (C) 2006 Christian Schneider / NMedit project, based on Jan Punter\'s work, GPL.')
    out.append('#include "nmmmoduledb.h"')
    out.append('')
    out.append('namespace nmm')
    out.append('{')
    out.append('\tnamespace')
    out.append('\t{')
    mods = []
    for m in body.findall('m:module', NS):
        idx = int(m.get('index'))
        name = m.get('name')
        params = []
        customs = []
        for p in m.findall('m:parameter', NS):
            cls = p.get('class', 'parameter')
            pidx = int(p.get('index', '0'))
            mn = int(p.get('minValue', '0'))
            mx = int(p.get('maxValue', '127'))
            df = int(p.get('defaultValue', '0'))
            if cls == 'parameter':
                bits = 7 if (idx == 97 and pidx == 2) else max(mx, 1).bit_length()   # MasterOsc kbt: 7 bits on the wire
                pname = p.get('name', '').lower()
                onebased = pname in ('waveform', 'filter type', 'slope', 'partials')   # selectors that 2.10 stored 1-based (statistics over the patch archive)
                flags = (1 if 'out,assign' in p.get('role', '') else 0) | (2 if p.get('role', '') == 'mute' else 0) | (4 if onebased else 0)   # 1: 2.10 stores output destinations 1-based, 2: mute, inverted in 2.10, 4: selector 1-based in 2.10
                params.append((pidx, mn, mx, df, bits, flags, p.get('name')))
            elif cls == 'custom':
                customs.append((pidx, mn, mx, df, p.get('name')))
        conns = []
        for c in m.findall('m:connector', NS):
            conns.append((int(c.get('index')), 1 if c.get('type') == 'output' else 0, SIGNALS.get(c.get('signal', 'none'), 6), c.get('name')))
        mods.append((idx, name, params, customs, conns))
        out.append('\t\tconstexpr ParamDesc g_params_%d[] = {%s};' % (idx, ', '.join('{%d,%d,%d,%d,%d,%d}' % p[:6] for p in params) or '{0,0,0,0,0,0}'))
        out.append('\t\tconstexpr ParamDesc g_customs_%d[] = {%s};' % (idx, ', '.join('{%d,%d,%d,%d,8,0}' % c[:4] for c in customs) or '{0,0,0,0,0,0}'))
        out.append('\t\tconstexpr ConnDesc g_conns_%d[] = {%s};' % (idx, ', '.join('{%d,%d,%d}' % c[:3] for c in conns) or '{0,0,0}'))
    out.append('')
    out.append('\t\tconstexpr ModuleDesc g_modules[] = {')
    for idx, name, params, customs, conns in sorted(mods):
        out.append('\t\t\t{%d, "%s", g_params_%d, %d, g_customs_%d, %d, g_conns_%d, %d},' % (idx, esc(name), idx, len(params), idx, len(customs), idx, len(conns)))
    out.append('\t\t};')
    out.append('\t}')
    out.append('')
    out.append('\tconst ModuleDesc* ModuleDb::find(const int _index)')
    out.append('\t{')
    out.append('\t\tfor (const auto& m : g_modules)')
    out.append('\t\t\tif(m.index == _index) return &m;')
    out.append('\t\treturn nullptr;')
    out.append('\t}')
    out.append('')
    out.append('\tsize_t ModuleDb::count() { return sizeof(g_modules) / sizeof(g_modules[0]); }')
    out.append('\tconst ModuleDesc* ModuleDb::at(const size_t _i) { return &g_modules[_i]; }')
    out.append('}')
    with open(dst, 'w') as f:
        f.write('\n'.join(out) + '\n')
    print('%d modules -> %s' % (len(mods), dst))

if __name__ == '__main__':
    main()
